### ISSUE TITLE
Change CTA

### ISSUE THREAD

**Issue by KyleKrukar** [bythepixel/devhour#14]
- [x] change the CTA to: "Join us for our next DevHour on <b>9.28.17</b> about <b>Single-Page Applications</b>"

![screen shot 2017-08-14 at 12 00 21 pm](https://user-images.githubusercontent.com/2396445/29284476-29f61618-80e8-11e7-89c2-1073abf1ad2e.png)

**Comment by HeathNaylor** [comment]
We have a date for the next DevHour, shooting for September 28, same timeline as the last one, food at 5:30pm, DevHour from 6pm-7pm, drinks from 7pm on.

The topic is going to be Single Page Applications.
