### ISSUE TITLE
Write short description for "Single-page Applications" DevHour

### ISSUE THREAD

**Issue by KyleKrukar** [bythepixel/devhour#17]
- [ ] Short Paragraph

One of the placements will be facebook events (this is a draft):
<img width="510" alt="screen shot 2017-09-05 at 8 26 11 pm" src="https://user-images.githubusercontent.com/2396445/30091783-a9c13854-9278-11e7-8573-caa3a607d2b2.png">

**Comment by HeathNaylor** [comment]
Single-Page Applications (SPAs) are Web apps that load a single HTML page and dynamically update that page as the user interacts with the app. Popular examples of single-page apps include Twitter, Facebook and Gmail. This DevHour conceptualizes and walks through bootstrapping a React application with a Webpack build process and Redux data store.
