### ISSUE TITLE
Develop devhour.io

### ISSUE THREAD

**Issue by KyleKrukar** [bythepixel/devhour#3]
- [x] provisioning
- [x] include meta descriptions, titles etc. (to be provided)
- [ ] include content type markup (eg. place, date, title)
- [x] responsive
- [x] page-load animation
- [x] google analytics integration
- [x] contact form submissions
...

**Comment by KyleKrukar** [comment]
@NathanBurkett 

fonts: https://adobe.ly/2rIR6Mp
website files: https://adobe.ly/2sKyZUP

**Comment by NathanBurkett** [comment]
@KyleKrukar Looking back over this issue
> include content type markup (eg. place, date, title)

What sort of markup? [Microdata](http://schema.org/docs/gs.html)?

**Comment by KyleKrukar** [comment]
Yes, exactly @NathanBurkett. But this is more for when we advertise it publicly and are displaying more information surrounding the event. You can leave alone for now if you want to.
