### ISSUE TITLE
Setup Email Address

### ISSUE THREAD

**Issue by KyleKrukar** [bythepixel/devhour#4]
- [ ] contact@devhour.io
- [ ] plus, a catchall

**Comment by rreynier** [comment]
I have created devhour@bythepixel.com. Password `Btppass123!`

**Comment by rreynier** [comment]
I have not created contact@devhour.io, neither have I created a catchall.

**Comment by adam12** [comment]
Slacker.

**Comment by KyleKrukar** [comment]
@rreynier that password is incorrect. 
![video](https://user-images.githubusercontent.com/2396445/27099455-3e152552-5038-11e7-8938-3a067acff5c7.gif)

**Comment by rreynier** [comment]
Gif was necessary for me to understand the seriousness of this issue.
