### ISSUE TITLE
Write submission content for Docker talk

### ISSUE THREAD

**Issue by KyleKrukar** [bythepixel/devhour#5]
Develope Denver requirements:
- [x] Image
- [x] Title
- [x] Categories
- [x] Description

![screen shot 2017-05-30 at 2 50 04 pm](https://cloud.githubusercontent.com/assets/2396445/26604344/48a528e2-4547-11e7-9b46-6f90480f1ef3.png)

**Comment by HeathNaylor** [comment]
**Title:**
Docker for Developers
_or_
Containers for Developers

**Categories:**
Containers, LXC, Docker, Deployment, Microservices

**Description:**
As a developer you probably use or are familiar with virtual machines. Often times we use a combination of Vagrant and a virtualization technologies, such as VirtualBox or VMware, to aid in replicating our production environment locally. Containers are a shift away from VM's towards Virtual Environments (VE's). In this talk, I am going to discuss our implementation of Docker and how it has aided in decoupling services and streamlined our deploy processes. We will discuss the simplest ways to implement containers in your development and deploy processes, and touch on scaling and container orchestration. This talk is intended for people who have had little to no exposure to containers in general, or those who have containers running in production and are curious about other implementations.

**Comment by KyleKrukar** [comment]
https://developdenver.org/talks/64
